FROM ubuntu

CMD sudo apt-get -y update && sudo apt-get -y upgrade && sudo apt-get install -y python3.10 && sudo apt-get install -y git && sudo apt install -y python3-pip && git clone https://github.com/Yashvi10/PythonFlaskWebApplication && cd PythonFlaskWebApplication && pip3 install flask && pip3 install requests && python3 main.py