FROM ubuntu

CMD apt-get -y update && apt-get -y upgrade && apt-get install -y python3.10 && apt-get install -y git && apt install -y python3-pip && git clone https://github.com/Yashvi10/PythonFlaskWebApplication && cd PythonFlaskWebApplication && pip3 install flask && pip3 install requests && python3 main.py